#spring:
#  application:
#    name: taskmanagement
#  datasource:
#    url: jdbc:postgresql://localhost:5432/taskmanagement?createDatabaseIfNotExist=true
#    username: postgres
#    password: enigma
#  jpa:
#    show-sql: true
#    properties:
#        hibernate:
#          jdbc:
#            lob:
#              non_contextual_creation: true
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: true
#    hibernate:
#      ddl-auto: create-drop
#server:
#  port: 8081